# Generated by Django 6.0.2 on 2026-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField()),
                ('related_plants', models.ManyToManyField(blank=True, related_name='care_tips', to='plants.plant')),
            ],
        ),
    ]
