# Generated by Django 6.0.2 on 2026-02-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('light_level', models.CharField(choices=[('LOW', 'Low Light'), ('MED', 'Medium Light'), ('HIGH', 'Direct Sunlight')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('height_cm', models.FloatField(help_text='Height in centimeters')),
                ('water_needs_ml', models.PositiveSmallIntegerField(help_text='Water per week in milliliters')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='plants.room')),
            ],
        ),
    ]
