# Generated by Django 6.0.2 on 2026-02-11 18:16

import plants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, validators=[plants.validators.validate_start_with_capital]),
        ),
    ]
